"""add_display_name_to_companies

Revision ID: c4acc39a8be2
Revises: ed2a57123cd6
Create Date: 2026-05-17 01:21:47.885982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4acc39a8be2'
down_revision: Union[str, None] = 'ed2a57123cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('display_name', sa.String(length=500), nullable=True))
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=512),
               comment='Raw SEC EDGAR legal name — preserved for audit traceability',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Raw SEC EDGAR legal name — preserved for audit traceability',
               existing_nullable=False)
    op.drop_column('companies', 'display_name')
    # ### end Alembic commands ###
