"""initial schema

Revision ID: f09c9c08ba9d
Revises: 
Create Date: 2026-05-16 18:31:31.819430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09c9c08ba9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False, comment='10-digit zero-padded SEC CIK'),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('sector', sa.String(length=256), nullable=True),
    sa.Column('industry', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('eval_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filing_accession', sa.String(length=25), nullable=False),
    sa.Column('expected_has_going_concern', sa.Boolean(), nullable=False),
    sa.Column('expected_severity', sa.String(length=16), nullable=True),
    sa.Column('expected_flag_type', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_cases_filing_accession'), 'eval_cases', ['filing_accession'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_token')
    )
    op.create_index(op.f('ix_subscriptions_email'), 'subscriptions', ['email'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False, comment='e.g. 10-K, 10-Q, 8-K'),
    sa.Column('accession_number', sa.String(length=25), nullable=False, comment='SEC accession number'),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('filing_url', sa.Text(), nullable=False),
    sa.Column('raw_text_path', sa.Text(), nullable=True, comment='Path or object-storage key to stored full text'),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_accession_number'), 'filings', ['accession_number'], unique=True)
    op.create_index('ix_filings_company_filing_date', 'filings', ['company_id', 'filing_date'], unique=False)
    op.create_index(op.f('ix_filings_company_id'), 'filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_filings_filing_date'), 'filings', ['filing_date'], unique=False)
    op.create_index(op.f('ix_filings_form_type'), 'filings', ['form_type'], unique=False)
    op.create_table('auditor_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filing_id', sa.UUID(), nullable=False, comment='One auditor report per filing'),
    sa.Column('audit_firm', sa.String(length=256), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=False, comment='Extracted auditor report section'),
    sa.Column('extraction_method', sa.String(length=64), nullable=False, comment='e.g. html_section_xpath, fuzzy_match'),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id')
    )
    op.create_table('going_concern_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('flag_type', sa.String(length=16), nullable=False),
    sa.Column('quoted_language', sa.Text(), nullable=False, comment='Exact paragraph cited from the auditor report'),
    sa.Column('char_offset_start', sa.Integer(), nullable=False, comment='Byte offset within auditor report text'),
    sa.Column('char_offset_end', sa.Integer(), nullable=False),
    sa.Column('classification_confidence', sa.Numeric(precision=4, scale=3), nullable=False, comment='e.g. 0.987'),
    sa.Column('classifier_version', sa.String(length=64), nullable=False, comment='e.g. v1.0-claude-sonnet-4'),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gcf_detected_at', 'going_concern_flags', ['detected_at'], unique=False)
    op.create_index('ix_gcf_severity_detected_at', 'going_concern_flags', ['severity', 'detected_at'], unique=False)
    op.create_index(op.f('ix_going_concern_flags_company_id'), 'going_concern_flags', ['company_id'], unique=False)
    op.create_index(op.f('ix_going_concern_flags_filing_id'), 'going_concern_flags', ['filing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_going_concern_flags_filing_id'), table_name='going_concern_flags')
    op.drop_index(op.f('ix_going_concern_flags_company_id'), table_name='going_concern_flags')
    op.drop_index('ix_gcf_severity_detected_at', table_name='going_concern_flags')
    op.drop_index('ix_gcf_detected_at', table_name='going_concern_flags')
    op.drop_table('going_concern_flags')
    op.drop_table('auditor_reports')
    op.drop_index(op.f('ix_filings_form_type'), table_name='filings')
    op.drop_index(op.f('ix_filings_filing_date'), table_name='filings')
    op.drop_index(op.f('ix_filings_company_id'), table_name='filings')
    op.drop_index('ix_filings_company_filing_date', table_name='filings')
    op.drop_index(op.f('ix_filings_accession_number'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_subscriptions_email'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_eval_cases_filing_accession'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
